name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Prepare SSH key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key

    - name: Create directory on VM
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p /home/$USERNAME/hello-api"

    - name: Print sayHelloAPI.js (Local)
      run: cat sayHelloAPI.js

    - name: Deploy to VM
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        scp -i ssh_key -o StrictHostKeyChecking=no -r * $USERNAME@$HOST:/home/$USERNAME/hello-api
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "
        pm2 stop sayHelloAPI || true &&
        pm2 delete sayHelloAPI || true &&
        cd /home/$USERNAME/hello-api &&
        npm install &&
        pm2 start sayHelloAPI.js --name sayHelloAPI &&
        pm2 save
        "

    - name: Print sayHelloAPI.js (VM)
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "cat /home/$USERNAME/hello-api/sayHelloAPI.js"

    - name: Verify deployment
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "ls -l /home/$USERNAME/hello-api"

    - name: Check PM2 logs
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "pm2 logs sayHelloAPI"
